name: Feature request
description: Suggest a change
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem you want solved
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What you have in mind
